# version: '3.3'
# services:

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/

# version: '3.3'
# services:

#   db:
#     image: postgres:13-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     restart: always
#     env_file:
#       - ./.env

#   backend:
#     image: pendu1um/final_backend
#     restart: always
#     volumes:
#       - static_value:/app/static/
#       - media_value:/app/media/
#     depends_on:
#       - db
#     env_file:
#       - ./.env

#   frontend:
#     image: pendu1um/final_frontend
#     volumes:
#       - ../frontend/:/app/result_build/
#     depends_on: 
#       - db

#   nginx:
#     image: pendu1um/final_nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/
#       - static_value:/var/html/static/ 
#       - media_value:/var/html/media/
#     depends_on:
#       - backend
#       - frontend

# volumes:
#   postgres_data:
#   static_value:
#   media_value:

version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: pendu1um/final_backend
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    image: pendu1um/final_frontend
    volumes:
      - ../frontend/:/app/result_build/


  nginx:
    image: pendu1um/final_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/